const E=[
['Trek','Marlin 5','Gen 1','CYC Photon Gen 2','reported','A completed owner conversion is documented with a component list.','Not reported','No structural modification reported.','https://www.reddit.com/r/ebikes/comments/1rjitn5/trek_marlin_5_g1_with_cyc_photon_gen_2/','38T chainring and CYC A52L battery reported.'],
['Trek','Marlin 5','Unspecified','CYC Photon','reported','A completed build is shown by an owner.','Not reported','No fit issue reported.','https://www.reddit.com/r/ebikes/comments/1cfz63h/cyc_photon_on_my_trek_marlin_5/','Model year and frame size still need verification.'],
['Trek','Marlin 5','2022','Bafang BBS02','question','A buyer compares BBS02 with CYC Photon before purchase.','Not reported','Chainline uncertainty influences the decision.','https://www.reddit.com/r/ebikes/comments/15z5mg6/is_the_cyc_photon_worth_the_extra_money/','Demand evidence only; not a completed installation.'],
['Trek','Marlin 5','2018','Bafang BBSHD','question','A buyer asks whether BBS02 or BBSHD is the better conversion.','Not reported','No completed build established by this page.','https://www.reddit.com/r/ebikes/comments/hzl8qc/2018_trek_marlin_5_ebike_conversion/','Compatibility remains unverified.'],
['Trek','Marlin 5','Unspecified','Bafang BBSHD','modified','A fitment problem is reported when using a 68 mm motor in a 73 mm shell.','73 mm (owner report)','Grinding, spacers and bolt length are discussed.','https://www.reddit.com/r/bafang/comments/10d6sc9/bbshd_1000w_52v_fitment_issues_trek_marlin_5/','Measure the actual frame before buying.'],
['Trek','Marlin 6','2022','Bafang BBSHD','question','A prospective installation is discussed.','72/73 mm threaded (poster report)','Spacer and chainline concerns are unresolved.','https://electricbike.com/forum/forum/main-forum/general-discussions/147195-bafang-bbshd-on-trek-marlin-6-2022','No completed installation established.'],
['Trek','Marlin 6','Unspecified','Bafang BBSHD','guidance','Community members describe the frame as conversion-friendly.','Not reported','Potential bottom-bracket grinding is raised.','https://www.reddit.com/r/ebikes/comments/y8z62g/wanting_to_electrify_my_marlin_6_helpsuggestions/','General guidance, not exact fit evidence.'],
['Trek','Marlin 7','2021','Bafang BBS02','reported','A completed owner build is documented.','Not reported','Supporting components were upgraded.','https://www.emtbforums.com/threads/bafang-bbshd-advice-please.34240/','Large frame, 36V 500W and 10-speed drivetrain reported.'],
['Trek','Marlin 7','Unspecified','Bafang BBSHD','reported','A completed build is shown in a video.','Not reported','Installation details require extraction.','https://www.youtube.com/watch?v=3znvNqkxdqg','Year and frame size remain unknown.'],
['Specialized','Rockhopper','2021','Bafang BBS02','reported','A completed build is shown by the owner.','Not reported','No modification reported.','https://www.reddit.com/r/ebikes/comments/pw5ocx/my_bafang_bbs02_on_a_2021_specialized_rockhopper/','13Ah battery and photo evidence.'],
['Specialized','Rockhopper 29','2012','Bafang BBSHD','reported','The owner says the installation went together well.','Not reported','Correct crank and pedal tools were needed.','https://www.reddit.com/r/ebikes/comments/qj3bx3/specialized_rock_hopper_29_bafang_bbshd_conversion/','Single owner report.'],
['Specialized','Rockhopper','2019','Bafang BBSHD','conflict','The motor was installed, but the owner could not achieve a usable chainline.','Not reported','Chain dropping and shifting problems were reported.','https://www.reddit.com/r/ebikes/comments/178fviy/2019_rockhopper_better_fit_bbs02_or_bbshd/','High-value warning; results may vary by frame.'],
['Giant','Talon 4','Unspecified','Bafang BBSHD','reported','A completed owner installation is documented.','Not reported','No fit modification reported.','https://www.reddit.com/r/ebikes/comments/przcsy/my_new_giant_talon_4_bbshd_ebike/','48V 17.5Ah battery reported.'],
['Giant','Talon 1','2022','Bafang BBSHD','modified','The motor was installed, but the chain falls off on the largest rear sprocket.','Not reported','Chainring offset or another chainline solution is required.','https://www.reddit.com/r/ebikes/comments/12ukdm3/bafang_on_a_giant_talon_1_chain_line_issue/','10-speed cassette reported.'],
['Giant','Talon 3','Unspecified','Bafang BBSHD','reported','A completed build is shown.','Not reported','Detailed installation information is incomplete.','https://www.reddit.com/r/ebikes/comments/gewk8x/giant_talon_3_bbshd_build_on_a_pier/','29-inch wheel mentioned.'],
['Trek','6000','circa 2000','CYC Photon','reported','A completed owner conversion is documented.','Not reported','Fork and handlebar were changed for the use case.','https://www.reddit.com/r/ebikes/comments/1e1t336/trek_6000_cyc_photon_conversion/','Used for a 16-mile commute.']];
const $=id=>document.getElementById(id),unique=a=>[...new Set(a)],brand=$('brand'),model=$('model'),year=$('year'),kit=$('kit'),result=$('result');
function opts(el,a){el.innerHTML=a.map(x=>`<option>${x}</option>`).join('')}
function models(){opts(model,unique(E.filter(x=>x[0]===brand.value).map(x=>x[1])));years()}
function years(){opts(year,unique(E.filter(x=>x[0]===brand.value&&x[1]===model.value).map(x=>x[2])));kits()}
function kits(){opts(kit,unique(E.filter(x=>x[0]===brand.value&&x[1]===model.value).map(x=>x[3])))}
opts(brand,unique(E.map(x=>x[0])));models();brand.onchange=models;model.onchange=years;year.onchange=kits;
const titles={reported:'Reported completed installation',modified:'Reported fit with problems or modifications',conflict:'Conflicting or unsuccessful fit report',question:'Not enough evidence',guidance:'General guidance only'};
$('check').onclick=()=>{const x=E.find(x=>x[0]===brand.value&&x[1]===model.value&&x[2]===year.value&&x[3]===kit.value);const subject=encodeURIComponent(`Fitment request: ${brand.value} ${model.value} ${year.value} × ${kit.value}`),body=encodeURIComponent(`Bike: ${brand.value} ${model.value}\nYear: ${year.value}\nKit: ${kit.value}\nFrame size:\nBottom bracket measurement:`);result.classList.remove('hidden');result.innerHTML=x?`<div class="status ${x[4]}"><small>EVIDENCE STATUS</small><h2>${titles[x[4]]}</h2></div><h3>${x[3]}</h3><p class="sub">${x[0]} ${x[1]} · ${x[2]}</p><div class="grid"><article><small>WHAT WAS OBSERVED</small><p>${x[5]}</p></article><article><small>BOTTOM BRACKET</small><p>${x[6]}</p></article><article><small>MODIFICATIONS / RISKS</small><p>${x[7]}</p></article><article><small>RESEARCH NOTE</small><p>${x[9]}</p></article></div><div class="actions"><a href="${x[8]}" target="_blank" rel="noopener">View original owner source ↗</a><a href="mailto:fociva.tech@gmail.com?subject=${subject}&body=${body}">Submit your build</a></div>`:`<div class="status question"><small>NO EXACT RECORD</small><h2>We do not have enough evidence for this combination.</h2></div><p>This does not mean it will not fit. It means we cannot support a claim yet.</p><div class="actions"><a href="mailto:fociva.tech@gmail.com?subject=${subject}&body=${body}">Request this combination →</a></div>`;result.scrollIntoView({behavior:'smooth',block:'center'});};
